feeds:
  - name: "TechCrunch"
    url: "https://techcrunch.com/feed/"
  - name: "Hacker News"
    url: "https://news.ycombinator.com/rss"
  - name: "The Verge"
    url: "https://www.theverge.com/rss/index.xml"
  - name: "BBC News"
    url: "http://feeds.bbci.co.uk/news/rss.xml"
  - name: "The Guardian (World)"
    url: "https://www.theguardian.com/world/rss"
  - name: "ESPN FC"
    url: "http://www.espnfc.com/rss"
  - name: "BBC Sport - Football"
    url: "http://feeds.bbci.co.uk/sport/football/rss.xml"
  - name: "Variety"
    url: "https://variety.com/feed/"