feeds:
  - name: "TechCrunch"
    url: "https://techcrunch.com/feed/"
  - name: "BBC News"
    url: "http://feeds.bbci.co.uk/news/rss.xml"
  - name: "BBC Sport - Football"
    url: "http://feeds.bbci.co.uk/sport/football/rss.xml"
